spring.application.name=Ayurkisan-Ecommerce
server.port=8080

spring.data.mongodb.uri=mongodb+srv://Ayurkisan-Ecommerce:Ayurkisan2026@ayurkisan-ecommerce.eyvf3lu.mongodb.net/ayurkisan_db?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
# ---- HARD STOP FOR STARTUP NOISE ----
spring.main.banner-mode=off
spring.main.log-startup-info=false

# ---- LOGGING CONTROL ----
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.apache.catalina=ERROR

# Allow ONLY these two
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
logging.level.com.ayurkisan=INFO

# ---- CLEAN OUTPUT (NO TIMESTAMP / THREAD) ----
logging.pattern.console=%msg%n
